url_random_list = ["http://www.example.com/","https://www.example.com/","https://example.com/books/arch#airplane","https://example.com/","http://www.example.com/","http://www.example.com/?bike=beds","https://www.example.com/birthday","https://example.com/","https://www.example.com/?airport=bone&board=bead","http://example.com/bite/account","http://example.org/angle/actor","http://example.com/box.html?bubble=achiever","https://www.example.net/","http://boot.example.com/bee.html","http://example.com/birds/beef.htm#brass","https://www.example.com/birthday?ball=boy","http://airplane.example.edu/","https://bubble.example.org/","https://www.example.net/attack/boot.php","http://example.com/?badge=boy&bomb=arm","http://www.example.com/blade/border?baby=aunt","http://example.net/","https://www.example.com/bath","https://example.com/","http://www.example.com/#bird","http://www.example.com/","http://www.example.org/approval","https://blow.example.com/agreement","https://www.example.com/","http://www.example.com/","https://bubble.example.com/aunt?arithmetic=brick","http://basin.example.com/","http://www.example.com/","https://example.com/brother/animal.html","http://example.com/beds.html","https://www.example.net/","http://www.example.com/boundary/believe","http://www.example.com/baseball/bubble","https://www.example.com/?aunt=addition&birds=appliance","http://www.example.org/bath","http://example.com/basin","https://beef.example.com/branch/beef.php","http://example.net/base.php","http://www.example.com/appliance.php","https://example.com/amount","http://www.example.com/action/authority","http://example.edu/","http://arm.example.com/","https://www.example.com/","http://example.com/"]


domain_random_list = ["zaplishany.com","humlicible.com","eismapenan.com","vildalaint.com","diffaitarm.com","dandimakov.com","sarcariais.com","dandiceopo.com","jandosthil.com","fornianite.com","seriembowe.com","rastuishem.com","dumionaged.com","buttengspy.com","kichacitip.com","aescumamal.com","nappianeoc.com","oariamordt.com","taroiseigo.com","ampoisherv.com","straiplinn.com","dispitmacs.com","naboomeary.com","aitiandunt.com","bidnalmark.net","miceakenaw.net","lunmicerit.net","ficloopous.net","pophouitte.net","sorticulel.net","corieshacc.net","embrolagog.net","titheprows.net","posmermaru.net","jassisatha.net","burairpelm.net","nontutioax.net","fossamatal.net","hugeollink.net","ronnuenant.net","bascotetez.net","mulsanstin.net","nodleronos.net","voldepindi.net","oppmatians.net","hastesrain.net","dellielist.net","sephousint.net","copainfrak.net","sasmearrot.net"]


user_agent_random_list = ["Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36","Mozilla/5.0 (Linux; Android 4.1.2; GT-S7390L Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.82 Mobile Safari/537.36","Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36","Apache-HttpClient/4.5.7 (Java/11.0.2)","Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)","Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:62.0) Gecko/20100101 Firefox/62.0","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36","Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0","Mozilla/5.0 (Windows; U; Windows NT 5.1; pt-PT; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729)","Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36","Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.9.0 Lightning/5.4.9","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"]

bot_user_agent_random_list = ["Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)", "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; AdsBot-Google-Mobile; +http://www.google.com/mobile/adsbot.html)", "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)", "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)", "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)", "Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)", "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)", "Mozilla/5.0 (compatible; ScoutJet; http://www.scoutjet.com/)", "Mozilla/4.0 compatible ZyBorg/1.0 DLC (wn.zyborg@looksmart.net; http://www.WISEnutbot.com)", "Mozilla/4.0 compatible ZyBorg/1.0 Dead Link Checker (wn.zyborg@looksmart.net; http://www.WISEnutbot.com)", "Mozilla/4.0 compatible ZyBorg/1.0 Dead Link Checker (wn.dlc@looksmart.net; http://www.WISEnutbot.com)", "Mozilla/4.0 compatible ZyBorg/1.0 (wn.zyborg@looksmart.net; http://www.WISEnutbot.com)", "Mozilla/4.0 compatible ZyBorg/1.0 (wn-16.zyborg@looksmart.net; http://www.WISEnutbot.com)", "Mozilla/4.0 compatible ZyBorg/1.0 (wn-14.zyborg@looksmart.net; http://www.WISEnutbot.com)", "ia_archiver/8.9 (Windows NT 3.1; en-US;)", "ia_archiver/8.9 (Windows 3.9; en-US;)", "ia_archiver/8.9 (Linux 1.0; en-US;)", "ia_archiver", "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)", "Linguee Bot (http://www.linguee.com/bot; bot@linguee.com)"]

location_random_data = [ ["SA","BR","Sao Paulo"], ["SA","BR","Rio De Janeiro"], ["SA","BR","Belo Horizonte"], 
    ["SA","AR","La Plata"], ["SA","AR","Santa Rosa"], ["SA","AR","Pergamino"], 
    ["SA","CL","Santiago"], ["SA","CL","Concepcion"], ["SA","CL","Valparaiso"], 
    ["SA","CO","Bogota"], ["SA","CO","Medellin"], ["SA","CO","Barranquilla"], 
    ["SA","PE","Lima"], ["SA","PE","Arequipa"], ["SA","PE","Cajamarca"], 
    ["NA","US","Ashburn"], ["NA","US","Mountain View"], ["NA","US","Chicago"], 
    ["NA","CA","Toronto"], ["NA","CA","Vancouver"], ["NA","CA","Ottawa"] ]
